---
title: "EDA overall time series"
author: "Chloé Lepert"
date: "5/9/2018"
output: pdf_document
---

Notes:
# Excluding data prior to 2012

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
library(ggplot2)
library(TTR)
library(xts)
library(readr)
load("~/Documents/30850/PSETs/project/30850Project/5and10percentSample.RData")
weather <- read_csv("~/Documents/30850/PSETs/project/30850Project/Weather/NOAA_weather_data.csv")
financials <- read_csv("~/Documents/30850/PSETs/project/30850Project/financials.csv")
source("smaller_df.R")
```

```{r}
overall.daily = aggregate.daily.strong.no.type(df10)
overall.daily = overall.daily[overall.daily$Start.date >= "2012-01-01", ]
overall.daily$log.Freq = log(overall.daily$Freq)
```

# Daily traffic
```{r}
ggplot(overall.daily, aes(x = Start.date, y = log.Freq)) + geom_line()
```


```{r}
trend = lm(log.Freq ~ poly(Start.date, 2), overall.daily)
summary(trend)
```

```{r}
overall.daily$trend = fitted(trend)

ggplot(overall.daily, aes(x = Start.date)) + geom_line(aes(y = log.Freq)) + 
  geom_line(aes(y = trend))
```

```{r}
overall.daily$de.trended = overall.daily$log.Freq - overall.daily$trend
ggplot(overall.daily, aes(x = Start.date)) + geom_line(aes(y = de.trended))
```

```{r}
overall.daily$month = month(overall.daily$Start.date)
overall.daily$year = year(overall.daily$Start.date)
season = lm(de.trended ~ as.factor(month), overall.daily)
overall.daily$season = fitted(season)
summary(season)
```

```{r}
ggplot(overall.daily, aes(x = Start.date)) + geom_line(aes(y = de.trended)) +
  geom_line(aes(y = season), color = "red")
```

```{r}
overall.daily$remain = overall.daily$de.trended - overall.daily$season
ggplot(overall.daily, aes(x = Start.date, y = remain)) + geom_line()
```

```{r}
trend.season = lm(log.Freq ~ poly(year, 2) + as.factor(month), overall.daily)
summary(trend.season)
```

# Weather data
```{r}
library(stringr)
weather[is.na(weather) == TRUE] = 0

convert.weather.date = function(date.str) {
  spl = str_split(date.str, "/")[[1]]
  if(nchar(spl[1]) == 1){
    spl[1] = paste("0", spl[1], sep = "")
  }
  if(nchar(spl[2]) == 1){
    spl[2] = paste("0", spl[2], sep = "")
  }
  date = as.Date(paste(spl[3], spl[1], spl[2], sep = "-"))
  return(date)
}

date.list = as.list(weather$DATE)
new.date.list = list()
for(i in 1:length(date.list)) {
  new.date.list[[i]] = convert.weather.date(date.list[[i]])
}


weather$date = as.Date(unlist(new.date.list))
daily.weather = merge(overall.daily, weather, by.x = "Start.date", 
                      by.y = "date", all.x = T)
```

# Weather as predictor
```{r}
no.weather = lm(log.Freq ~ poly(year, 2) + as.factor(month), daily.weather)
weather = lm(log.Freq ~ poly(year, 2) + as.factor(month) + poly(AWND, 2) + poly(PRCP, 2) +
               poly(SNOW, 2) + poly(TMAX, 2) + poly(TMIN, 2), daily.weather)
summary(weather)
```

# Adding in financials - Note no financials for the weekend (we should detrend with weekends tho)
```{r}
financials$date = as.character(financials$date)
financials$date = paste(substr(financials$date, 1, 4), 
                        substr(financials$date, 5, 6),
                        substr(financials$date, 7, 8), sep = "-")
financials$date = as.Date(financials$date)
```

```{r}
daily.weather.fin = merge(daily.weather, financials, by.x = "Start.date", by.y = "date", all.x = T)
```

```{r}
weather = lm(log.Freq ~ poly(year, 2) + as.factor(month) + poly(AWND, 2) + poly(PRCP, 2) +
               poly(SNOW, 2) + poly(TMAX, 2) + poly(TMIN, 2), daily.weather)
weather.fin = lm(log.Freq ~ poly(year, 2) + as.factor(month) + poly(AWND, 2) + 
                   poly(PRCP, 2) + poly(SNOW, 2) + poly(TMAX, 2) + poly(TMIN, 2) +
                   cny + eur + gbp + jpy + snp_index + snp_daily_return + vix + 
                   vxo,
                 daily.weather.fin)
summary(weather.fin)
```

